FROM lcr.loongnix.cn/library/debian:forky-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    build-essential \
    openjdk-21-jdk-headless \
    git \
    wget \
    curl \
    unzip \
    cargo \
    cmake \
    golang \
    python3 \
    python3-pip \
    zlib1g-dev \
    libyaml-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install passlib --break-system-packages

# bazel
RUN wget -O /usr/bin/bazel https://github.com/loongarch64-releases/bazel/releases/download/7.5.0/bazel_nojdk-7.5.0-linux-loongarch64 \
    && chmod +x /usr/bin/bazel \
    && bazel --version

# nfpm
ENV GOPATH=/tmp/go 
RUN go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

# luajit2
RUN git clone -b v2.1-agentzh-loongarch64 --depth 1 https://github.com/loongson/luajit2.git /tmp/luajit2

CMD ["/bin/bash"]
